theme: jekyll-theme-hacker
title: Raven2Six's homepage
description: Thanks for stopping by.  Most of the information shared on this page is my notes - unfiltered and raw - of various personal projects I am working on.  The remainder is a combination of my thoughts on various industry topics as well as some information about me and my skillset. Feel free to drop me a line
show_downloads: false

![Octocat](https://github.githubassets.com/images/icons/emoji/octocat.png)
